<?php 
include('subs/header.php');

function metatag()
{
	echo '<title>Crwe World | Terms</title>';
}

?>
<style>
.col-md-12 a {
  color: #D20B0B;
}
</style>

<!-- WRAPPER-->
<div id="wrapper"><!-- PAGE WRAPPER-->
    <div id="page-wrapper"><!-- MAIN CONTENT-->
        <div class="main-content"><!-- CONTENT-->
            <div class="content">
                <div class="container">
                    <div class="row">
                    	
						<div class="col-md-12">
							<h2 class="mb-sm mt-sm">Terms & <strong style="color: #CC0101">Conditions</strong></h2>
                            <br>

<p>Welcome to the CRWEworld.com website. Although you may be tempted to skim over some of this—indeed, there is some "legalese" involved—we hope you'll read it through. We'll do our best to help you understand everything so you can feel good about contributing to your local CRWEWORLD.</p>
<p>In the grand scheme of things, the Site is a service (hereafter, together, the "Service") designed to make your life better. The Service is operated by Crown Equity Holdings Inc., d/b/a CRWEWORLD, "we" or "our"). By accessing or using the Service, through a personal computer, mobile device or any other means, you agree to be bound by these terms and conditions of Use. We ask that you read these Terms &amp; Conditions carefully before registering or using the Service. If you do not accept these Terms of Use, you may not use the Service.</p>
<p>Just like your local community, CRWEWORLD is growing and changing every day, and thus the Terms of Use are subject to change by CRWEWORLD at any time. However, we'll always let you know when the latest update occurred—just check the "Effective Date" on the bottom of this page. If you keep using the Service afterward, we assume that you have accepted the new Terms of Use.</p>
<h3>Use of the Service</h3>
<p>You may use this Service solely for personal and non-commercial purposes. That is to say: You can't use the Service to make a living or for any other purpose or in any other manner unless you enter into a separate written agreement with us that says you can. <strong> With the exception of any content located on this site from PR Newswire, GlobeNewswire, Business Wire, Accesswire or any other third party generated information</strong>, you may download and print a single copy of the content of the Service solely for your personal, non-commercial use and provided that you do not delete or modify any copyright or other proprietary notice. <strong>The redistribution of PR Newswire, GlobeNewswire, Business Wire, Accesswire or any third party content is strictly prohibited, as well as using any trade, logos or licenses marks of any content provider with their service</strong>. Keep in mind that all applicable laws, rules and regulations and any agreements or terms with third parties to which you are subject still apply.</p>
<p>In order to comprehensively cover your community, the Service contains information on businesses, establishments, public services and other third parties, as well as news, feature stories, images, video, audio and other materials. The Service may provide you with other ways to access and use such information and materials—for instance, we give you the option to receive our emails and bookmark our items in other social networking services. We try to ensure everything passes muster, but CRWEWORLD makes no guarantee that any information provided or accessed on or through the Service is accurate, current or complete. Your use of the information we provide or that you obtain on or through the Service is at your own risk. If you think something looks fishy, please let us know. You agree that you will not hold CRWEWORLD liable for any inaccurate, incomplete, outdated or missing information on the Service.</p>
<h3>Terms of Service</h3>
<p>By accessing CRWE World's web site (<a href="http://www.crweworld.com">www.crweworld.com</a>), you are agreeing to be bound by these web site Terms and Conditions of Use, all applicable laws and regulations, and agree that you are responsible for compliance with any applicable local laws. If you do not agree with any of these terms, you are prohibited from using or accessing this site. The materials contained in this web site are protected by applicable copyright and trade mark law.</p>
<h3>Registration</h3>
<p>We want everyone to enjoy CRWEWORLD, so you may use the Service without registration (i.e., signing up with a name, email address and password). However, in order to access some aspects of the Service, you will need to register for an account. Your account is for your sole, personal use. You may not allow others to use your account and you may not assign or otherwise transfer your account to any other person or entity. (If another person or entity wants an account, they can easily sign up themselves.) We ask that the e-mail address you provide when you register be a valid e-mail address for you. We encourage, but do not require, that the user name you provide be your real name. You are responsible for the security of your password and will be solely liable for any use or unauthorized use under such password. Therefore, if you share a computer with others, don't allow your Internet browser to automatically save your password. Also, don't write your password on a Post-It note and leave it on your desk for all to see.</p>
<h3>Use License</h3>
<p>CRWEWORLD is built to let you do fun things such as share text, and other information (all of which we call "Your Content"). When you do this, you own Your Content except as you may otherwise agree. However (and here comes some legalese), by sharing or uploading Your Content, you grant CRWEWORLD (and any of CRWEWORLD's contractors and licensors with respect to any of Your Content you provide to them through your use of our Site) a perpetual, worldwide license to use, redact, republish, copy, perform and distribute Your Content and your screen name, including, without limitation, any intellectual property contained therein, in any medium now known or hereinafter developed without payment or compensation to you and without seeking any further approval from you. We may also use your name, likeness, publicly accessible biographical data and any other information in connection with such use of Your Content. You acknowledge that our use of Your Content may include licensing Your Content to third parties and/or using Your Content for advertising purposes. In no event will we be required to seek your approval or provide you with any compensation in connection with any such uses. You acknowledge that nothing contained within Your Content would require us to seek permission of a third party in order to use Your Content as described in these Terms of Use. All that may sound like a lot, but these rights are primarily designed to give us legal protection—we're not looking to go into the "your business"</p>
<p>a. Permission is granted to temporarily download one copy of the materials (information or software) on CRWE WORLD's web site for personal, non-commercial transitory viewing only. This is the grant of a license, not a transfer of title, and under this license you may not:</p>
<p>i. modify or copy the materials;<br />
ii. use the materials for any commercial purpose, or for any public display (commercial or non-commercial);<br />
iii. attempt to decompile or reverse engineer any software contained on CRWEWORLD's web site;<br />
iv. remove any copyright or other proprietary notations from the materials; or<br />
v. transfer the materials to another person or "mirror" the materials on any other server.</p>
<p>b. This license shall automatically terminate if you violate any of these restrictions and may be terminated by CRWE WORLD at any time. Upon terminating your viewing of these materials or upon the termination of this license, you must destroy any downloaded materials in your possession whether in electronic or printed format.</p>
<h3>Acceptable Use</h3>
<p>While we encourage people to be honest and post what's on their mind, communities thrive when people care about each other, and as such, CRWEWORLD expects all of its users to be respectful of others. This means that whether you are being complimentary or critical, whether you are agreeing or disagreeing with the subject of an article or another user's comment, you should act in a civil manner and refrain from personal attacks – after all, these are your neighbors.</p>
<p>CRWEWORLD is under no obligation to enforce the CRWEWORLD Terms of Use on your behalf or based on a claim by you that another user has breached any of these Terms of Use. While we encourage you to let us know if you believe that another user has breached these Terms of Use or has engaged in other unacceptable behavior, by reporting it to <a href="mailto:support@CRWEWorld.com">support@CRWEWorld.com</a> will make the sole determination, in CRWEWORLD's sole discretion, as to whether Your Content or any other content is acceptable for the Service. (Someone has to be in charge, right?) Because CRWEWORLD provides a platform for wide-ranging commentary – both positive and negative – by members of local communities, you should keep in mind that, even if you disagree with or object to a comment or review, CRWEWORLD typically does not remove comments or reviews in response to requests from users. CRWEWORLD's role is not to arbitrate disagreements between community members and local businesses, or among community members. And (for the lawyers out there) the law doesn't require us to perform that role in order to keep offering what we think is a valuable community service: providing a platform for community discussion, debate and expression of opinions on the topics at hand.</p>
<p>By using the Service, you agree that you will not hold CRWEWORLD responsible or liable for any content or information from other users that you access on or through the Service.</p>
<p>You are solely responsible for Your Content that you post on the Service or transmit to other users. Without limitation, you agree that Your Content that you post or transmit to other users using the Service will not include any content that:</p>
<p>• is defamatory, abusive, obscene, profane or offensive;<br />
• infringes or violates another party's intellectual property rights (such as music, videos, photos or other materials that you do not own, or for which you do not have written consent from the owner of such materials to post on the Service);<br />
• violates any party's right of publicity or right of privacy;<br />
• is threatening, harassing or that promotes racism, bigotry, hatred or physical harm of any kind against any group or individual;<br />
• promotes or encourages violence;<br />
• is inaccurate, false or misleading in any way;<br />
• is illegal or promotes any illegal activities;<br />
• promotes illegal or unauthorized copying of another person's copyrighted work or links to them or providing information to circumvent security measures;<br />
• contains "masked" profanity (e.g., F@&amp;#)<br />
• contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment; or contains or links to any advertising, promotional materials, "junk mail," "spam," "chain letters," "pyramid schemes," or any other form of solicitation.</p>
<p>Instead of trying to memorize all that, you might boil it down to three main principles: "Keep it clean," "Don't try to trick people," and "Treat others as you'd like to be treated."</p>
<h3>Disclaimer</h3>
<p>a. The materials on CRWEWORLD's web site are provided "as is". CRWEWORLD makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties, including without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights. Further, CRWEWORLD does not warrant or make any representations concerning the accuracy, likely results, or reliability of the use of the materials on its Internet web site or otherwise relating to such materials or on any sites linked to this site.</p>
<p>We do our best to keep tabs on what is posted on the Service; however CRWEWORLD is under no obligation to screen or monitor any content, but may review content from time to time at its sole discretion to determine compliance with the CRWEWORLD Terms of Use. CRWEWORLD will make all determinations as to what content is appropriate, at its sole discretion. We may include, edit or remove any content at any time and without notice.</p>
<p>Variety is the spice of digital life, so understand that when using the Service, you will be exposed to content and communications from a variety of sources and that CRWEWORLD is not responsible for the accuracy, usefulness, safety, or intellectual property rights of or relating to any such content. And, just like when you visit any website, by using CRWEWORLD you acknowledge that you may be exposed to content that is inaccurate, offensive, indecent or objectionable. If you object to this possibility, you should not use the Service.</p>
<p>In keeping with our "Don't trick anyone" request, you may not use spiders, robots, data mining techniques or other automated devices or programs to catalog, download or otherwise reproduce, store or distribute content available on the Service. Further, you may not use any such automated means to manipulate the Service or attempt to exceed the limited authorization and access granted to you under these Terms of Use. You may not resell use of, or access to, the Service to any third party.</p>
<h3>Please note that:</h3>
<p>CRWEWorld, a division of Crown Equity Holdings, Inc., publishes, distributes information compiled from outside sources. The report/release/advertisement for on this website and on or newsletter and reports such as the company's stock alerts highlights and advertisements is for general information purposes only.</p>
<p><strong>DO NOT BASE ANY INVESTMENT DECISION UPON ANY INFORMATION FOUND ON THIS WEBSITE. PLEASE BE ADVISED THAT YOUR CONTINUED USE OF THIS SITE OR THE INFORMATION PROVIDED HEREIN SHALL INDICATE YOUR CONSENT AND AGREEMENT TO THESE TERMS.</strong></p>
<p><strong>Never invest in any stock featured on our site or emails unless you can afford to lose your entire investment. The disclaimer is to be read and fully understood before using our site, or joining our email list.</strong></p>
<p>Neither CRWEWorld (Crown Equity Holdings, Inc.) nor its employees and affiliates are registered as investment advisors or broker/dealers in any jurisdiction whatsoever. Through use of this website viewing or using you agree to hold CRWEWorld, its operators, owners, employees, and affiliates harmless and to completely release them from any and all liability due to any and all loss (monetary or otherwise), damage (monetary or otherwise), or injury (monetary or otherwise) that you may incur. The information contained herein is based on sources that we believe to be reliable but is not guaranteed by us as being accurate and does not purport to be a complete statement or summary of the available data. Readers should always do their own due diligence and consult a financial professional. CRWEWorld encourages readers and investors to supplement the information in these reports with independent research and other professional advice. All information on featured companies is provided by the companies profiled, or is available from public sources and CRWEWorld makes no representations, warranties or guarantees as to the accuracy or completeness of the disclosure by the profiled company. Any opinions expressed on this website are statements of judgment as of the date of publication and are subject to change without further notice, and may not necessarily be reprinted in future publications or elsewhere.</p>
<p>None of the materials or advertisements herein constitute offers or solicitations to purchase or sell securities of the company profiled herein and any decision to invest in any such company or other financial decisions should not be made based upon the information provide herein. Instead, CRWEWorld strongly urges you to conduct a complete and independent investigation of the respective companies and consideration of all pertinent risks. CRWEWorld does not offer such advice or analysis, and CRWEWorld further urges you to consult your own independent tax, business, financial and investment advisors. Investing in micro-cap and growth securities is highly speculative and carries and extremely high degree of risk. It is possible that an investor's investment may be lost or impaired due to the speculative nature of the company profiled. Occasionally CRWEWorld is compensated to feature certain companies. These third party, may have shares and may liquidate it, which may negatively affect the stock price. This compensation constitutes a conflict of interest as to our ability to remain objective in our communication regarding the profiled company. CRWEWorld, its operators, owners, employees, and affiliates may have interests or positions in equity securities of the companies profiled on this website, some or all of which may have been acquired prior to the dissemination of this report, and may increase or decrease these positions at any time.</p>
<p>This website may contain forward-looking statements, which involve risks and uncertainties. Accordingly, no assurance can be given that the actual events and results will not be materially different than the anticipated results described in the forward-looking statement. There are a number of important factors that could cause actual results to differ materially from those expressed in any forward-looking statements made by CRWEWorld about the companies profiled. These factors include those companies' success in their business and operations; the activities of new or existing competitors, the ability to attract and retain employees and strategic partners, the ability to leverage intangible assets, the ability to complete new projects at planned costs and on planned schedules and adoption of the Internet as a medium of commerce, communications and learning. If applicable, investors are also directed to consider other risks and uncertainties discussed in documents filed by the profiled companies with the Securities and Exchange Commission. CRWEWorld undertakes no obligation to publicly release the result of any revisions to these forward-looking statements, which may be made to reflect events or circumstances after the date hereof or to reflect the occurrence of unanticipated events.</p>
<p>The services provided by this website and its contents are provided "as is" and CRWEWorld makes no representations or warranties of any kind with respect to this website, its contents or its services. This website has been prepared solely for the purpose of providing information about CRWEWorld and the services it offers. This website has been compiled in good faith by CRWEWorld. CRWEWorld assumes no liability or responsibility for any errors or omissions in the content of this website, any failures, delays, or interruptions in its services or any content contained on this website, any losses or damages arising from the use of the content provided on this website, or any conduct by users of CRWEWorld's services. CRWEWorld reserves the right to add, modify or delete any information at this website at any time.</p>
<p>CRWEWorld does not represent or warrant that any other website which you may access through this one is accurate, complete, or current. While, such other websites are believed to be reliable, CRWEWorld and its owners, affiliates, subsidiaries, officers, directors, representatives and agents disclaim any liability as to the completeness or accuracy of the information contained in any such website and for any omissions of materials facts from such websites. When you access another website through this one, please understand that it is independent from CRWEWorld and that CRWEWorld has no control over the content on that website, and CRWEWorld is not responsible for any claims made by that website. In addition, a link to a non-CRWEWorld website is not an indication that CRWEWorld endorses or accepts any responsibility for the content, or the use, of such website.</p>
<p>In no event shall CRWEWorld, its operators, owners, employees, and affiliates be liable (jointly or severally) for any special, incidental, indirect or consequential damages of any kind, or any damages whatsoever resulting from loss of use, data or profits, whether or not advised of the possibility of damage, and on any theory of liability, arising out of or in connection with the use or performance of CRWEWorld's website, its contents or its services. If any applicable authority holds any portion of this section to be unenforceable, then liability will be limited to the fullest possible extent permitted by applicable law.</p>
<h3>Limitations</h3>
<p>In no event shall CRWEWORLD or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption,) arising out of the use or inability to use the materials on CRWEWORLD's Internet site, even if CRWEWORLD or a CRWEWORLD authorized representative has been notified orally or in writing of the possibility of such damage. Because some jurisdictions do not allow limitations on implied warranties, or limitations of liability for consequential or incidental damages, these limitations may not apply to you.</p>
<h3>Revisions and Errata</h3>
<p>The materials appearing on CRWEWORLD's web site could include technical, typographical, or photographic errors. CRWEWORLD does not warrant that any of the materials on its web site are accurate, complete, or current. CRWEWORLD may make changes to the materials contained on its web site at any time without notice. CRWE WORLD does not, however, make any commitment to update the materials.</p>
<h3>Links</h3>
<p>CRWEWORLD has not reviewed all of the sites linked to its Internet web site and is not responsible for the contents of any such linked site. The inclusion of any link does not imply endorsement by CRWEWORLD of the site. Use of any such linked web site is at the user's own risk.</p>
<p>In order to provide you with as much relevant information as possible, the Service may contain links to other web sites not maintained by us. The links may include listings that provide you with further information, or links that have been included in materials uploaded to the Service by a party other than CRWEWORLD. Be aware when you leave our Service and read the terms and conditions and privacy statements of each and every website you visit, even if they are not as charming as ours. We are not responsible for the practices or the content of such other websites or services. Despite any links that might exist on the Service, we do not endorse and are not affiliated with such third parties.</p>
<h3>Site Terms of Use Modifications</h3>
<p>CRWEWORLD may revise these terms of use for its web site at any time without notice. By using this web site you are agreeing to be bound by the then current version of these Terms and Conditions of Use.</p>
<h3>Governing Law</h3>
<p>Any claim relating to CRWEWORLD's web site shall be governed by the laws of the State of Nevada, USA without regard to its conflict of law provisions.</p>
<h3>Termination of Access</h3>
<p>We want to keep CRWEWORLD a safe and friendly place, so in addition to any right or remedy that may be available to us under these Terms of Use or applicable law, we may suspend, limit or terminate your account, or all or a portion of your access to the Service, at any time with or without notice and with or without cause. In addition, we may refer any information on illegal activities, including your identity, to the proper authorities – that includes the police and/or your parents.</p>
<h3>Privacy</h3>
<p>The privacy of your personally identifiable information is very important to us. For more details on what information we collect and how we use it, please read our <a href="http://crweworld.com/privacy_policy" target="_blank">Privacy Policy</a>. The Services is not directed at children, and CRWEWORLD will not knowingly collect personally identifiable information from any child under age 13.</p>
<h3>Our Proprietary Rights</h3>
<p>We work hard on our materials and (surprise) require that you don't steal them. CRWEWORLD or its licensors are the exclusive owners of all content, copy, software, graphics, designs and all copyrights, trademarks and other intellectual property or proprietary rights contained on or used in connection with the Service. Except as set forth herein, you agree not to copy, distribute, modify or make derivative works of any materials without the prior written consent of the owner of such materials. All rights not granted under these Terms of Use are reserved by CRWEWORLD. If you want to use something but think it might belong to us, please ask before taking it.</p>
<h3>No Warranties</h3>
<p>THE SERVICE, INCLUDING ALL CONTENT MADE AVAILABLE ON OR ACCESSED THROUGH THE SERVICE, IS PROVIDED "AS IS" AND "AS AVAILABLE." WE MAKE NO REPRESENTATIONS OR WARRANTIES OF ANY KIND WHATSOEVER FOR OR WITH RESPECT TO THE CONTENT ON THE SERVICE. FURTHER, TO THE FULLEST EXTENT PERMISSIBLE BY LAW, WE DISCLAIM ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, ANY IMPLIED WARRANTY OF NON-INFRINGEMENT, TITLE, MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. WE DO NOT WARRANT THAT THE FUNCTIONS CONTAINED IN THE SERVICE OR ANY MATERIALS OR CONTENT CONTAINED THEREIN WILL BE COMPLETELY SECURE, UNINTERRUPTED OR ERROR FREE, THAT DEFECTS WILL BE CORRECTED, OR THAT THE SERVICE OR THE SERVER THAT MAKES IT AVAILABLE ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. WE SHALL NOT BE LIABLE FOR THE USE OF THE SERVICE, INCLUDING, WITHOUT LIMITATION, THE CONTENT AND ANY ERRORS CONTAINED THEREIN PROVIDED BY THIRD PARTIES. IN NO EVENT WILL WE BE LIABLE UNDER ANY THEORY OF TORT, CONTRACT, STRICT LIABILITY OR OTHER LEGAL OR EQUITABLE THEORY FOR ANY DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR OTHER CONSEQUENTIAL DAMAGES, LOST PROFITS, LOST DATA, LOST OPPORTUNITIES, COSTS OF COVER, EXEMPLARY, PUNITIVE, PERSONAL INJURY/WRONGFUL DEATH, EACH OF WHICH IS HEREBY EXCLUDED BY AGREEMENT OF THE PARTIES REGARDLESS OF WHETHER OR NOT WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. AS USED IN THIS SECTION, "WE" AND "OUR" INCLUDES CRWEWORLD AND CRWEWORLD'S CONTRACTORS AND LICENSORS.</p>
<p>If any part of these warranty disclaimers or limitations of liability is found to be invalid or unenforceable for any reason, or if we are otherwise found to be liable to you in any manner, then our aggregate liability for all claims under such circumstances for liabilities shall not exceed the lesser of (a) the amount paid by you for your use of the Service during the prior twelve (12) months or (b) ten dollars ($10).</p>
<h3>Indemnity</h3>
<p>We made these Terms for a reason. Therefore we can't be held responsible if you disregard them. You agree to defend, indemnify and hold harmless Crown Equity Holdings Inc., its officers, directors, employees, business partners and agents, and their respective heirs, successors and assigns, from and against any and all claims, damages, obligations, losses, liabilities, costs or debt, and expenses (including, but not limited to, attorney's fees) arising from: (a) any breach or alleged breach by you of any of these Terms of Use, (b) Your Content, (c) your use of materials or features available on the Service (except to the extent a claim is based upon infringement of a third party right by materials created by CRWEWORLD) or (d) a violation by you of applicable law or any agreement or terms with a third party to which you are subject.</p>
<h3>Governing Law</h3>
<p>Because the CRWEWORLD HQ is located in Nevada, we have to play by Nevada's rules. That's why the laws of the State of Nevada will govern these Terms of Use. YOU HEREBY EXPRESSLY CONSENT TO EXCLUSIVE JURISDICTION AND VENUE IN THE COURTS LOCATED IN CLARK COUNTY/LAS VEGAS IN NEVADA FOR ALL MATTERS ARISING IN CONNECTION WITH THESE TERMS OF USE OR YOUR ACCESS OR USE OF THE SERVICE.</p>
<p>Any claims asserted by you in connection with the Service must be asserted in writing to CRWEWORLD within one (1) year of the date such claim first arose, or such claim is forever waived by you. Each claim shall be adjudicated individually, and you agree not to combine your claim with the claim of any third party.<br />
<p><strong>Digital Millennium Copyright Act</strong></p>
<p><strong>A)</strong> If you are a copyright owner or an agent thereof and believe that any Content infringes upon your copyrights, you may submit a notification pursuant to the Digital Millennium Copyright Act ("DMCA") by providing our Copyright Agent with the following information in writing (see 17 U.S.C 512(c)(3) for further detail):</p>
<p>- A physical or electronic signature of a person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed;<br />
- Identification of the copyrighted work claimed to have been infringed, or, if multiple copyrighted works at a single online site are covered by a single notification, a representative list of such works at that site;<br />
- Identification of the material that is claimed to be infringing or to be the subject of infringing activity and that is to be removed or access to which is to be disabled and information reasonably sufficient to permit the service provider to locate the material;<br />
- Information reasonably sufficient to permit the service provider to contact you, such as an address, telephone number, and, if available, an electronic mail;<br />
- A statement that you have a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law; and<br />
- A statement that the information in the notification is accurate, and under penalty of perjury, that you are authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.</p>
<p>You may direct copyright infringement notifications to our DMCA Agent at 11226 Pentland Downs Street., Las Vegas, NV 89141, email: <a href="mailto:copyright@crweworld.com">copyright@crweworld.com</a>. For clarity, only DMCA notices should go to the Copyright Agent; any other feedback, comments, requests for technical support, and other communications should be directed to CRWE World customer service through <a href="mailto:support@crweworld.com">support@crweworld.com</a>. You acknowledge that if you fail to comply with all of the requirements of this Section 5(D), your DMCA notice may not be valid.</p>
<p><strong>B)</strong> <strong>Counter-Notice</strong>. If you believe that your Content that was removed (or to which access was disabled) is not infringing, or that you have the authorization from the copyright owner, the copyright owner's agent, or pursuant to the law, to post and use the material in your Content, you may send a counter-notice containing the following information to the Copyright Agent:</p>
<p>-Your physical or electronic signature;<br />
-Identification of the Content that has been removed or to which access has been disabled and the location at which the Content appeared before it was removed or disabled;<br />
-A statement that you have a good faith belief that the Content was removed or disabled as a result of mistake or a misidentification of the Content; and<br />
-Your name, address, telephone number, and e-mail address, a statement that you consent to the jurisdiction of the federal court in San Francisco, California, and a statement that you will accept service of process from the person who provided notification of the alleged infringement.</p>
<p>If a counter-notice is received by the Copyright Agent, CRWE World may send a copy of the counter-notice to the original complaining party informing that person that it may replace the removed Content or cease disabling it in 10 business days. Unless the copyright owner files an action seeking a court order against the Content provider, member or user, the removed Content may be replaced, or access to it restored, in 10 to 14 business days or more after receipt of the counter-notice, at CRWE World's sole discretion.</p>

<h3>Electronic Communication</h3>
<p>By accessing or using the Service, registering, sending an email or otherwise communicating with CRWEWORLD through the Service, you are communicating with CRWEWORLD electronically, and you agree to receive electronic communication from CRWEWORLD, by email and by posting to the Site. You agree that any electronic communication from CRWEWORLD satisfies any legal requirements that such communication must be in writing. You also agree that any communications or materials that you provide to CRWEWORLD or the Service, including, without limitation, by posting to the Service, email or otherwise, are and will be treated as non-confidential and non-proprietary.</p>
<h3>General</h3>
<p>The Service is controlled and operated by Crown Equity Holdings Inc., (d/b/a CRWEWORLD) from its headquarters in Las Vegas, Nevada, USA. CRWEWORLD makes no representation that any content on the Service is appropriate or available for use in other locations. You are solely responsible for ensuring that your access to and use of the Service complies with all applicable laws, statutes and regulations of your jurisdiction, including, without limitation, export and import regulations. CRWEWORLD reserves the right, in its sole discretion, to terminate your access to the Service, or to modify or discontinue the Service, in whole or in part, at any time and without notice. You agree that CRWEWORLD will have no liability to you or to any third party for any termination, modification, or discontinuance of the Service.</p>
<h3>Severability</h3>
<p>We consider our Terms of Use to exist as individual parts of a larger whole. If any part of these Terms of Use are held or declared to be invalid or unenforceable for any reason by any court of competent jurisdiction, such provision shall be ineffective but shall not affect any other part of these Terms of Use. This means that even if one part of these Terms of Use is judged unsound, the rest still apply.</p>
<h3>Waiver; Remedies</h3>
<p>One last bit of "legalese": The failure by us to partially or fully exercise any rights or the waiver of any breach of these Terms of Use by you will not prevent a subsequent exercise of such right by us or be deemed a waiver by us of any subsequent breach by you of the same or any other term of these Terms of Use. Our rights and remedies under these Terms of Use are cumulative, and the exercise of any such right or remedy will not limit our right to exercise any other right or remedy.</p>
<p><u>Translation</u>: If you do something that's prohibited by these Terms of Use but don't get caught, that doesn't mean it's OK, it just means we didn't catch you. There's still a perfectly good chance that we will catch you the next time and it won't be OK.</p>
<h3>Contact Us</h3>
<p>If you have any questions or comments about our Terms of Use or anything else, you may contact us at: Crown Equity Holdings Inc., d/b/a CRWEWORLD Attn: Copyright Officer 11226 Pentland Downs Street, Las Vegas, Nevada 89141 Email: <a href="mailto:support@CRWEWorld.com">support@CRWEWorld.com</a> or <a href="mailto:copyright@CRWEWORLD.com">copyright@CRWEWORLD.com</a>. Effective Date: These Terms of Use were last updated on August 11, 2015.</p>
	


<br><br>
						</div>
					</div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php include('subs/footer.php') ?>